language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
before_install:
  - chmod +x ./build.sh
script:
  - ./build.sh --quiet verify
  - mono ./packages/xunit.runners.*/tools/xunit.console.clr4.exe /home/travis/build/gonzalompp/dotnetcore-travisci/src/Calculator.Tests/bin/Debug/netcoreapp2.0/Calculator.Tests.dll
